{{- if .Values.sonar.deploy -}}
apiVersion: v2.edp.epam.com/v1alpha1
kind: Sonar
metadata:
  name: sonar
spec:
  edpSpec:
    dnsWildcard: {{ .Values.global.dnsWildCard }}
  type: Sonar
  initImage: {{.Values.sonar.initImage}}
  dbImage: {{.Values.sonar.dbImage}}
  image: {{.Values.sonar.image}}
  version: {{.Values.sonar.version}}
  basePath: {{.Values.sonar.basePath}}
  imagePullSecrets: {{.Values.sonar.imagePullSecrets}}
  volumes:
    - capacity: {{ .Values.sonar.dataVolumeCapacity }}
      name: data
      storage_class: {{ .Values.sonar.dataVolumeStorageClass }}
    - capacity: {{ .Values.sonar.dbVolumeCapacity }}
      name: db
      storage_class: {{ .Values.sonar.dbVolumeStorageClass }}
{{end}}