name: sonar-operator
namespace: ""
platform: "openshift"
dnsWildcard: ""
image:
  name: epamedp/sonar-operator
  version: v2.3.0
  
sonar:
  deploy: true
  name: "sonar"
  image: "sonarqube"
  version: "7.9-community"
  
edp:
  dnsWildCard: "delivery.aws.main.edp.projects.epam.com"  