global:
  edpName: ""
  platform: "openshift"
  dnsWildCard: "delivery.aws.main.edp.projects.epam.com"

name: sonar-operator
image:
  name: epamedp/sonar-operator
  version: v2.4.0

resources:
  limits:
    cpu: 200m
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 64Mi

sonar:
  deploy: true
  name: "sonar"
  image: "sonarqube"
  version: "7.9-community"
  initImage: "busybox"
  dbImage: "postgres:9.6"
  basePath: ""
  imagePullSecrets:
  storage:
    data:
      class: gp2
      size: 1Gi
    database:
      class: gp2
      size: 1Gi

  resources:
    limits:
      cpu: 2
      memory: 3Gi
    requests:
      cpu: 500m
      memory: 1.5Gi
