{{- if eq .Values.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: Role for admin-console-operator-edp service account
    openshift.io/reconcile-protect: "false"
  name: sonar-operator-role-{{ .Values.namespace }}
rules:
- apiGroups:
    - '*'
   attributeRestrictions: null
   resources:
     - securitycontextconstraints
  verbs:
     - patch
     - update
     - delete
     - get
     - list
     - create
- apiGroups:
    - '*'
  attributeRestrictions: null
   resources:
     - gerrits
     - gerrits/finalizers
     - gerrits/status
     - gerritreplicationconfigs
     - gerritreplicationconfigs/status
   verbs:
     - '*'
- apiGroups:
    - '*'
   attributeRestrictions: null
   resources:
     - keycloaks
     - keycloaks/status
     - keycloakclients
     - keycloakclients/finalizers
     - keycloakclients/status
     - keycloakrealms
     - keycloakrealms/status
     - sonars
     - sonars/finalizers
     - sonars/status
     - edpcomponents
   verbs:
    - '*'
{{ end }}
