apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "sonar-data"
  labels:
    app: sonar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sonar.storage.data.size }}
  storageClassName: {{ .Values.sonar.storage.data.class }}
  volumeMode: Filesystem