apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "sonar-db"
  labels:
    app: sonar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sonar.storage.database.size }}
  storageClassName: {{ .Values.sonar.storage.database.class }}
  volumeMode: Filesystem