apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonar-db
  name: sonar-db
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: sonar-db
  sessionAffinity: None
  type: ClusterIP